### ISSUE TITLE
Keysight N5221A PNA support?

### ISSUE THREAD

**Issue by 0xCoto** [WVURAIL/rflab_test#1]
Hi there, I am not very familiar with this API. Just wanted to ask, could the code be applicable to the Keysight N5221A PNA model, or is it not supported? My goal is to simply fetch `s2p` data from the VNA.

**Comment by PranavSanghavi** [comment]
Hi Apostolos 
This repository is a legacy backup of software for some of our lab equipment and it desperately needs verification and some heavy servicing. I have had another script developed to acquire S-parameters that automatically gets said parameters from the network Analyser. A version of it lives here https://github.com/WVURAIL/Antenna_Test_Files .  It however needs to be refactored a bit and pushed online. I shall it done tomorrow and I’ll ping with the update. 

But from my understanding it would work with most Keysight network analyzers to get the s parameters. 

Pranav Sanghavi

**Comment by 0xCoto** [comment]
Thanks, looking forward to it!

**Comment by PranavSanghavi** [comment]
@0xCoto here it is https://github.com/WVURAIL/keysight_network_analyser_control 
`/measure_two_port_s_paramters.py` should do what you need. I think all that is needed is to separately download the Keysight libraries and specify the .dll file. I have not gotten to get this supported on linux I just cannot seem to get the Keysight libraries installed yet.

**Comment by 0xCoto** [comment]
@PranavSanghavi Thank you very much for the script! I actually struggled with finding the `.dll` file myself (I am a complete beginner with the VISA protocol etc. and have never interfaced with the VNA over an external machine before, but I did read here and there that a `.dll` file might be needed).

Where exactly could I find a download for this? Is it instrument/model-specific, and do I only need to import this on my machine, or also on the VNA?

As for the physical connectivity, do you just have to hook up a LAN cable from the computer to the VNA (with any particular network configurations?), or is there more to it?

> I have not gotten to get this supported on linux I just cannot seem to get the Keysight libraries installed yet.

I'd also ideally like to get this running on Linux, but otherwise I'll try to do something with Windows. Is the problem that the `.dll` is OS-specific, or do you actually need to run some VISA/Keysight software?

**Comment by PranavSanghavi** [comment]
@0xCoto so for the `.dll` best way to do this is to install IO libraries from https://www.keysight.com/zz/en/lib/software-detail/computer-software/io-libraries-suite-downloads-2175637.html  can get either windows or linux. However I believe this would be a better place to download the libraries. https://pyvisa.readthedocs.io/en/latest/faq/getting_nivisa.html#faq-getting-nivisa . The Keysight libraries and software are useful to debug and develop.  
it is not instrument specific both VISA and the GP-IB (general purpose instrument bus) are standardised and used by most instrument vendors. 

in this function https://github.com/WVURAIL/rflab_test/blob/5c06d99fbfc1ccb6fdc2a524cf632eb62fdd2e18/keysight_na/measure_two_port_s_paramters.py#L141 
You load the .dll, and the object `rm` uses that to interface with the NA connected over LAN to get an instrument address using `rm.list_resources`. You need to make sure both NA and you computer are on the same LAN. The linux version of the library file should be a `*.so` file I think. 

BUT, You do not need specify `.dll` really. ! pyvisa should find it for you!  However the appropriate io libraries must be installed! Ostensibly for any operating system! I shall update the code to reflect this.

**Comment by PranavSanghavi** [comment]
links to get libraries 

- windows and macOS [here](https://pyvisa.readthedocs.io/en/latest/faq/getting_nivisa.html#faq-getting-nivisa)
- Linux [here](https://www.ni.com/en-us/support/downloads/drivers/download.ni-linux-device-drivers.html#409880)
- or can get from keysight  [here](https://www.keysight.com/us/en/lib/software-detail/computer-software/io-libraries-suite-downloads-2175637.html) 

I am quickly testing if these work.

**Comment by PranavSanghavi** [comment]
ok. I cannot verify is I can get this to work on linux and do not have the time to throughly check it or get it working. I can get the linux drivers to installed but cannot connect my instrument and macOS stuff just crashes. Only windows from libraries installed from Keysight work 100%

**Comment by PranavSanghavi** [comment]
The appropriate libraries are all there. If you are inclined to try and get this working on linux I would appreciate any documentation on how you succeeded. Until then this script shall only support windows.
